### ISSUE TITLE
Japanese Font and Text Format

### ISSUE THREAD

**Issue by yasushisakai** [pubpub/pubpub#171]
## Japanese Font rendering is strange, below is one proposal for the Font and Text formatting. The values are based on a typical paperback widely read in Japan.

I do not know if the current Pubpub detects the written language, but considering potential localisation, the below font maybe useful.
https://fonts.google.com/earlyaccess

Below is one possible proposal.

Font

``` html
<link href="https://fonts.googleapis.com/earlyaccess/notosansjapanese.css" type="text/css" rel="stylesheet">
```

given the width of the content size, Japanese are used to have 30-40 characters in one line.

Style

``` css
.atom-reader {
    font-family: 'Noto Sans Japanese', sans-serif;
    font-size: 0.94em;
    line-height: 1.59em;
    color: #333;
    letter-spacing: -0.02em;
}

.atom-reader h1, .atom-reader h2, .atom-reader h3, .atom-reader h4, .atom-reader h5, .atom-reader h6 {
    font-family: 'Noto Sans Japanese', sans-serif;
}

```

example rendering from Joi's post on accounting

![screen shot 2016-08-23 at 17 00 17](https://cloud.githubusercontent.com/assets/1502180/17909596/259eca7c-6953-11e6-9c97-9b5dd3d090a7.png)
